-- SOOP 스트리머 거리 맞추기 게임 리더보드
-- Supabase SQL Editor에서 실행하세요.

create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 20),
  score integer not null check (score >= 0 and score <= 10000),
  created_at timestamptz not null default now()
);

alter table public.leaderboard enable row level security;

drop policy if exists "Anyone can read leaderboard" on public.leaderboard;
create policy "Anyone can read leaderboard"
on public.leaderboard
for select
to anon
using (true);

drop policy if exists "Anyone can insert leaderboard score" on public.leaderboard;
create policy "Anyone can insert leaderboard score"
on public.leaderboard
for insert
to anon
with check (
  char_length(player_name) between 1 and 20
  and score >= 0
  and score <= 10000
);

create index if not exists leaderboard_score_created_idx
on public.leaderboard (score desc, created_at asc);
