// SOOP Graph Crawler with follower limit. Run inside Chrome DevTools Console on https://www.sooplive.com
(async()=>{
const CONFIG={seeds:["감스트","김봉준","김민교","우왁굳","철구","킴성태","타요"],maxDepth:3,maxNodes:200,maxBranches:5,delayMs:1500,minFollowers:10000,blockedIds:new Set(["2omong"]),blockedNicks:new Set(["이오몽","이오몽_"]),downloadJson:true,copyToClipboard:true};
const sleep=ms=>new Promise(r=>setTimeout(r,ms)), enc=t=>encodeURIComponent(encodeURIComponent(t));
function idFromLogo(url){const m=url?.match(/\/LOGO\/[^/]+\/([^/.]+)\.(jpg|png|webp)$/i);return m?m[1]:null}
function num(...vals){for(const v of vals){if(v===undefined||v===null||v==="")continue;const n=Number(String(v).replace(/,/g,""));if(!Number.isNaN(n))return n}return 0}
function norm(raw){if(!raw)return null;const id=raw.user_id||raw.bj_id||raw.id||raw.original_bj||idFromLogo(raw.station_logo);const nick=raw.user_nick||raw.nick||raw.nickname||raw.bj_nick||raw.station_name||raw.station_title||raw.bj_name||raw.user_name||null;const profileImage=raw.station_logo||raw.profile_image||raw.profileImage||null;const views=num(raw.total_view_cnt,raw.view_cnt,raw.totalViewCount);const followers=num(raw.fan_cnt,raw.follower_cnt,raw.follow_cnt,raw.favorite_cnt,raw.subscriber_cnt,raw.total_fan_cnt,raw.fan_count,raw.followers);if(!id&&!nick)return null;return{id,nick,search:nick||id,profileImage,views,followers}}
function allowed(s){return s&& !CONFIG.blockedIds.has(s.id)&&!CONFIG.blockedNicks.has(s.nick)&&s.followers>=CONFIG.minFollowers}
async function bjSearch(keyword){const url="https://sch.sooplive.com/api.php?l=DF&m=bjSearch&w=webk&isMobile=0&szType=json&c=UTF-8&v=5.0"+`&szKeyword=${enc(keyword)}`+"&nPageNo=1&nListCnt=40&szOrder=score&szTerm=1year&tab=bj&location=total_search&isHashSearch=0";const r=await fetch(url,{credentials:"include"});const text=await r.text();if(!text.trim().startsWith("{")){console.warn("Bad response",keyword,text.slice(0,300));return null}return JSON.parse(text)}
async function branches(keyword){const data=await bjSearch(keyword);if(!data)return{main:{id:keyword,nick:keyword,search:keyword,profileImage:null,views:0,followers:0},branches:[]};const main=norm(data.DATA?.[0])||{id:keyword,nick:keyword,search:keyword,profileImage:null,views:0,followers:0};const raw=data.RECOMMEND_DATA||[];const rec=raw.map(norm).filter(Boolean);if(rec.length&&rec.every(s=>!s.followers)){console.warn("Follower fields empty for",keyword);console.log("Raw keys:",Object.keys(raw[0]||{}));console.log(raw[0]);}const self=new Set([keyword,main.id,main.nick].filter(Boolean));const out=[],seen=new Set(self);for(const s of rec){if(!allowed(s))continue;if(seen.has(s.id)||seen.has(s.nick))continue;seen.add(s.id);seen.add(s.nick);s.search=s.nick||s.id;out.push(s);if(out.length>=CONFIG.maxBranches)break}return{main,branches:out}}
function addEdge(edges,set,a,b,nodes){if(!a||!b||a===b)return;const key=[a,b].sort().join("__");if(set.has(key))return;set.add(key);edges.push({a,b,aNick:nodes.get(a)?.nick||a,bNick:nodes.get(b)?.nick||b})}
function adj(edges){const a={};for(const e of edges){(a[e.a]??=[]).push(e.b);(a[e.b]??=[]).push(e.a)}for(const k of Object.keys(a))a[k]=[...new Set(a[k])];return a}
async function crawl(){const q=CONFIG.seeds.map(s=>({search:s,depth:0})), queued=new Set(CONFIG.seeds), visited=new Set(), nodes=new Map(), edges=[], edgeSet=new Set();while(q.length&&nodes.size<CONFIG.maxNodes){const cur=q.shift();console.log(`Crawling: ${cur.search} / depth ${cur.depth}`);let res;try{res=await branches(cur.search)}catch(e){console.error("Failed",cur.search,e);continue}const main=res.main,from=main.id||main.nick||cur.search;if(visited.has(from)||CONFIG.blockedIds.has(from)||CONFIG.blockedNicks.has(main.nick))continue;visited.add(from);nodes.set(from,main);console.log("Branches:",res.branches.map(b=>`${b.nick||b.id} (${b.followers})`));for(const b of res.branches){const to=b.id||b.nick;if(!to)continue;nodes.set(to,b);addEdge(edges,edgeSet,from,to,nodes);if(b.search&&cur.depth+1<=CONFIG.maxDepth&&!visited.has(to)&&!queued.has(b.search)){q.push({search:b.search,depth:cur.depth+1});queued.add(b.search)}}await sleep(CONFIG.delayMs)}const adjacency=adj(edges);const connected=new Set(Object.keys(adjacency));const finalNodes=[...nodes.values()].filter(n=>connected.has(n.id));const ids=new Set(finalNodes.map(n=>n.id));const finalEdges=edges.filter(e=>ids.has(e.a)&&ids.has(e.b));return{meta:{createdAt:new Date().toISOString(),graphType:"undirected",seeds:CONFIG.seeds,maxDepth:CONFIG.maxDepth,maxNodes:CONFIG.maxNodes,maxBranches:CONFIG.maxBranches,minFollowers:CONFIG.minFollowers,blockedIds:[...CONFIG.blockedIds],blockedNicks:[...CONFIG.blockedNicks],nodeCount:finalNodes.length,edgeCount:finalEdges.length,notes:"Follower-filtered crawl. profileImage is kept for game UI."},nodes:finalNodes,nodesById:Object.fromEntries(finalNodes.map(n=>[n.id,n])),edges:finalEdges,adjacency:adj(finalEdges)}}
const graph=await crawl();console.log("NODES");console.table(graph.nodes.map(n=>({id:n.id,nick:n.nick,followers:n.followers,views:n.views,profileImage:n.profileImage})));console.log("EDGES");console.table(graph.edges);console.log("FULL GRAPH",graph);const json=JSON.stringify(graph,null,2);try{typeof copy==="function"?copy(json):await navigator.clipboard.writeText(json);console.log("Graph JSON copied to clipboard.")}catch(e){console.warn("Clipboard failed",e)}if(CONFIG.downloadJson){const blob=new Blob([json],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="soop_graph_undirected.json";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);console.log("Download started: soop_graph_undirected.json")}
})();
